export const template_options = [
  {
    value: "buildheadless/headless/templates/hydrogen-theme",
    label: "Sanity x Hydrogen",
  },
];

export const welcomeMessages: string[] = [
  "Welcome! 😊 Let's get started!",
  "Hello there! 👋 Ready to dive in?",
  "Greetings! 🌟 Excited to have you here!",
  "Welcome aboard! 🚀 Get ready for the journey!",
  "Hey, welcome! 😄 Ready to have some fun?",
  "Welcome! 🎉 We've been waiting for you!",
  "Hello! 🌟 Get ready to create something awesome!",
  "Greetings! 🚀 Ready to embark on this adventure?",
  "Hey, welcome! 😊 Let's make magic happen!",
];

export const goodbyeMessages: string[] = [
  "Goodbye! 👋 Hope to see you again soon!",
  "Farewell! 🌟 Thanks for joining the journey!",
  "Until next time! 🚀 Take care and stay awesome!",
  "Goodbye for now! 😄 Keep creating magic!",
  "Adios! 🎉 It's been a pleasure having you!",
  "See you later! 🌟 Take on new adventures!",
  "Goodbye! 🚀 Until our paths cross again!",
  "Farewell, friend! 😊 Keep shining bright!",
  "Sayonara! 🌈 Wishing you all the best!",
];

export const cancelMessages: string[] = [
  "Cancelled! 😢 See you around!",
  "Action canceled! 😞 Take care!",
  "Canceled. 😭 Farewell, friend!",
  "Oops, action canceled! 😔 Until we meet again!",
  "Cancelled! 😢 Safe travels!",
  "Action canceled. 😞 Goodbye for now!",
  "Canceled! 😢 Take it easy!",
  "Oops, action canceled! 😭 Farewell, pal!",
  "Cancelled. 😔 See you soon!",
  "Canceled! 😞 It's been real!",
];

export const adjectives: string[] = [
  "quirky",
  "whimsical",
  "goofy",
  "lively",
  "zany",
  "droll",
  "silly",
  "witty",
  "kooky",
  "funky",
  "giddy",
  "groovy",
  "puzzled",
  "dizzy",
  "fluffy",
  "blithe",
  "sleek",
  "chirpy",
  "breezy",
  "dandy",
  "zesty",
  "sunny",
  "drifty",
  "chummy",
  "gloomy",
  "drowsy",
  "hasty",
  "dusky",
  "jumpy",
  "muggy",
  "woozy",
  "gloppy",
  "scrawny",
  "stumpy",
  "bumpy",
  "jumpy",
  "muddy",
  "foggy",
  "grumpy",
  "jolly",
  "wobbly",
  "snazzy",
  "blowy",
  "hasty",
  "fuzzy",
  "dizzy",
  "sloppy",
  "drippy",
  "gloppy",
  "breezy",
  "snoozy",
  "frumpy",
  "gimpy",
  "snappy",
  "crispy",
  "puffy",
  "flimsy",
  "shaggy",
  "shabby",
  "wheezy",
  "skinny",
  "craggy",
  "dorky",
  "lousy",
  "dopey",
  "flimsy",
  "gimpy",
  "gritty",
  "soggy",
  "grubby",
  "lousy",
  "gooey",
  "smelly",
  "goopy",
  "drippy",
  "creepy",
  "dingy",
  "foamy",
  "sappy",
  "schlumpy",
  "scraggy",
  "skanky",
  "slinky",
  "sludgy",
  "snarky",
  "sputtery",
  "squirmy",
  "sticky",
  "snoopy",
  "tacky",
  "hasty",
  "tippy",
  "grungy",
  "giddy",
  "wheezy",
  "blurry",
  "buzzy",
  "cranky",
  "hazy",
  "higgledy-piggledy",
  "mucky",
  "muzzy",
  "shaky",
  "sparky",
];

export const nouns: string[] = [
  "orion",
  "nova",
  "luna",
  "cosmo",
  "zara",
  "neo",
  "astra",
  "lyra",
  "cyra",
  "kairos",
  "pax",
  "calypso",
  "zephyr",
  "nyx",
  "cassiopeia",
  "atlas",
  "lyric",
  "rigel",
  "selene",
  "odin",
  "thalia",
  "seren",
  "orla",
  "alder",
  "thistle",
  "zinnia",
  "cypress",
  "saffron",
  "briar",
  "peregrine",
  "lark",
  "sable",
  "pippin",
  "hawthorn",
  "juniper",
  "ember",
  "rowan",
  "cirrus",
  "alder",
  "linden",
  "dune",
  "fable",
  "gale",
  "raven",
  "sorrel",
  "lynx",
  "hazel",
  "aster",
  "basil",
  "peregrine",
  "sorrel",
  "lynx",
  "hazel",
  "aster",
  "basil",
  "sparrow",
  "petal",
  "tansy",
  "birch",
  "clove",
  "finch",
  "fern",
  "raven",
  "wren",
  "alder",
  "sable",
  "thyme",
  "breeze",
  "dew",
  "pine",
  "heron",
  "quill",
  "sparrow",
  "pebble",
  "elm",
  "ash",
  "frost",
  "sparrow",
  "blossom",
  "flint",
  "frost",
  "alder",
  "fawn",
  "linden",
  "echo",
  "frost",
  "bloom",
  "dune",
  "dusk",
  "petal",
  "gale",
  "glen",
  "lark",
  "rain",
  "vale",
  "pine",
  "moss",
  "wisp",
  "brook",
  "cinder",
];
